# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6563db0d98042be5d4b6642eccbc398f51194d38c1695d3555c8bba2374f986088e5995978f9fefe5766686cc1e29661c3190dbdbe591fc7173b7b5526358623

test:
  secret_key_base: 94244af9097922d855a545453ff5daeb26d3b11246118a041daf81b8e23636a4b6dabd3a9c3d366d9739c975cb1792ba5f1bea9d1c39f67222570a5ba2cf4bcd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
